### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by colinf** [component/menu#1]
What is you intention with regard to browser support? Some things like Function.prototype.bind() and rgba in the CSS are not supported by all browsers.

They can be polyfilled or worked around but it would be good to know your thinking.

Thanks, Colin.

**Comment by tj** [comment]
yup just polyfills, or for example we have a `bind` component, but since eventually every browser will have it I'm not super worried about using a `bind` component for backwards compat, polyfill is fine for now

**Comment by tj** [comment]
as for the CSS that doesn't matter really, apps should define their own styles

**Comment by colinf** [comment]
Cool. Thanks.

**Comment by colinf** [comment]
For info, I have created a variant based on Menu, [Listbox Menu](http://github.com/colinf/listbox-menu). Not sure what your intentions are re component but happy to move this there if useful to you.

Cheers,
  Colin.

**Comment by tj** [comment]
nice :D, keeping them in your own repos is all-good, the package manager thing I'm working on will work fine like that they dont have to be under `component/*`

**Comment by colinf** [comment]
Great. I'll put it on to npm then and maybe create some more components as I move forwards. Cheers.
